# Linear algebra

This is a voluntary problem set that helps you to learn linear algebra (and the related numpy commands.)  Consult Greene "Econometric Analysis" Appendix A when solving these problems.

If handed in (and solved correctly ;-), it gives you 5 credits.


In [ ]:
print 'Pierre Augustamar'
print 'INFX 574A'

In [2]:
%matplotlib inline
import sympy as sympy
import numpy as np
import matplotlib.pyplot as plt
from scipy import *

## 1 Matrix multiplication
* create the following matrices:
a = [ 1 2 3 4], b = [5 6 7 8 ]'
(note: b includes the transposition sign)
* compute the following matrix products $a \cdot b$ and $a' \cdot b'$

In [3]:
a = np.array([1,2,3,4])
c = np.array([5,6,7,8])
b = c.reshape((1,4)).T

print a
print b
print
print 'a.b'
print a.dot(b)
print

a = a.reshape(1,4).T
print a
b = b.reshape(4, 1).T
print b
print 
print "a′⋅b′"

print a.dot(b)

[1 2 3 4]
[[5]
 [6]
 [7]
 [8]]

a.b
[70]

[[1]
 [2]
 [3]
 [4]]
[[5 6 7 8]]

a′⋅b′
[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]


## 2 Linear (in)dependence
Consider three vectors:
a = [1 2 3 4],
b = [5 6 7 8] and
c = [9 10 11 12]

* are these vectors linearly independent?  Calculate the rank, a related determinant, and show how they are related/unrelated

In [4]:
a = np.matrix('1 2 3 4')
b = np.matrix('5 6 7 8')
c = np.matrix('9 10 11 12')

A = np.row_stack([a, b, c])
print A

print 'rank' 
print 3
print 'vectors are not linearly independent'

print 'no relation between the rows'
              
print 'no related determinant as it is only possible for square matrix'

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rank
3
vectors are not linearly independent
no relation between the rows
no related determinant as it is only possible for square matrix


## 3 Find the inverses of the following matrices:


A = [ <br/>
    1 2 3 4 <br/>
5 6 7 8 <br/>
-1 10 11 12 <br/>
13 14 15 17 ],

B = [ <br/>
    1 0 0 <br/>
     0 4 0 <br/>
     0 0 16]

and

C = [ <br/>
    1 2 3 4 <br/>
      5 6 7 8 <br/>
      9 10 11 12 <br/>
      13 14 15 17 ]

* Check the results by left- and right multiplication of the inverse.  Explain.

In [19]:
a = np.matrix('1 2 3 4; 3 6 7 8; -1 10 11 12; 13 14 15 17')
print a
x = np.linalg.inv(a)
print x

print 'This matrix is left invertible and right invertible since it is a square matrix'


[[ 1  2  3  4]
 [ 3  6  7  8]
 [-1 10 11 12]
 [13 14 15 17]]
[[ -1.66666667e-01   3.33333333e-01  -1.66666667e-01   3.07446376e-16]
 [  1.33333333e+00  -4.41666667e+00   1.08333333e+00   1.00000000e+00]
 [ -4.50000000e+00   9.50000000e+00  -2.00000000e+00  -2.00000000e+00]
 [  3.00000000e+00  -5.00000000e+00   1.00000000e+00   1.00000000e+00]]


In [22]:
b = np.matrix('1 0 0; 0 4 0; 0 0 16')
print b
print 
z = np.linalg.inv(b)
print z

print 'This matrix is left invertible and right invertible since it is a square matrix'

[[ 1  0  0]
 [ 0  4  0]
 [ 0  0 16]]

[[ 1.      0.      0.    ]
 [ 0.      0.25    0.    ]
 [ 0.      0.      0.0625]]


In [24]:

c = np.matrix('1 2 3 4; 5 6 7 8; 9 10 11 12; 13 14 15 17')
print c
print
w =  np.linalg.inv(c)
print w
print 
print 'This matrix is left invertible and right invertible since it is a square matrix'

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 17]]

[[ -1.54070514e+15   3.08141027e+15  -1.54070514e+15  -4.70000000e-01]
 [  3.08141027e+15  -6.16282054e+15   3.08141027e+15   1.94000000e+00]
 [ -1.54070514e+15   3.08141027e+15  -1.54070514e+15  -2.47000000e+00]
 [  1.15789474e+00  -1.31578947e+00  -8.42105263e-01   1.00000000e+00]]

This matrix is left invertible and right invertible since it is a square matrix


## 4 Characteristic roots
* Find the roots (eigenvalues) of the matrices A, B, C above.
* Calculate the condition numbers of these matrices in two ways: the default numpy way, and in this way as it is explained in Greene (2003, page 829)
* Explain the results

In [48]:
a = np.matrix('1 2 3 4; 3 6 7 8; -1 10 11 12; 13 14 15 17')
print a
print
print np.linalg.eigvals(a)

print 'This matrix has the following eigenvalues: 35.67898331,  1.72904838,  -2.23387822,  -0.17415347'
print

print 'condition of this matrix is: %.5f' % np.linalg.cond(a)
print np.linalg.cond(a, 'fro')

import pandas as pd
print 'calculating  condition numbers based on Greene'
print
print 'condition number using Greene '

condition_number =np.linalg.norm(a)
print condition_number
print 'Both options gave a condition number greater than 20. Since the results are above 20 than this is worrisome'

[[ 1  2  3  4]
 [ 3  6  7  8]
 [-1 10 11 12]
 [13 14 15 17]]

[ 35.67898331   1.72904838  -2.23387822  -0.17415347]
This matrix has the following eigenvalues: 35.67898331,  1.72904838,  -2.23387822,  -0.17415347

condition of this matrix is: 492.15677
505.225815849
calculating  condition numbers based on Greene

condition number using Greene 
37.8549864615
Both options gave a condition number greater than 20. Since the results are above 20 than this is worrisome


In [47]:
b = np.matrix('1 0 0; 0 4 0; 0 0 16')
print np.linalg.eigvals(b)


print 'This matrix has the following eigenvalues: 1,   4,  1and 6'
print
print 'condition of this matrix is: %.5f' % np.linalg.cond(b)
print
print 'condition number using Greene '

condition_number =np.linalg.norm(b)
print condition_number
print
print 'Both options gave a value uner 20. Thus, this is not worrisome'

[  1.   4.  16.]
This matrix has the following eigenvalues: 1,   4,  1and 6

condition of this matrix is: 16.00000

condition number using Greene 
16.5227116419

Greene option gave a larger value than the numpy... possibly something wrong with m


In [51]:
c =  np.matrix('1 2 3 4; 5 6 7 8; 9 10 11 12; 13 14 15 17')
print np.linalg.eigvals(c)

print 'This matrix has the following eigenvalues: 3.66727818e+01  -2.00000000e+00  -2.08470091e-15   3.27218155e-01'

print
print 'condition of this matrix is: %.5f' % np.linalg.cond(c)

print 'condition number using Greene '

condition_number =np.linalg.norm(c)

print condition_number
print
print 'Both options gave a condition number greater than 20. Since the results are above 20 than this is worrisome'

[  3.66727818e+01  -2.00000000e+00  -2.08470091e-15   3.27218155e-01]
This matrix has the following eigenvalues: 3.66727818e+01  -2.00000000e+00  -2.08470091e-15   3.27218155e-01

condition of this matrix is: 76046968278614976.00000
condition number using Greene 
39.102429592

Both options gave a condition number greater than 20. Since the results are above 20 than this is worrisome
